Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -25,26 +25,51 @@ jobs:
       - name: Restore NuGet packages
         run: nuget restore Vesper.sln
 
-      - name: Download and Install Vulkan SDK
+      - name: Install Vulkan SDK
+        uses: humbletim/install-vulkan-sdk@v1.1.1
+        with:
+          version: 1.3.261.1
+          cache: true
+  
+      - name: Debug Vulkan SDK Installation
         run: |
-          curl -LO https://sdk.lunarg.com/sdk/download/1.3.261.1/windows/VulkanSDK-1.3.261.1-Installer.exe
-          start /wait VulkanSDK-1.3.261.1-Installer.exe /S /D=C:\VulkanSDK\1.3.261.1
-          set VULKAN_SDK=C:\VulkanSDK\1.3.261.1
-          set PATH=%VULKAN_SDK%\Bin;%PATH%
-          set PATH=%VULKAN_SDK%\Lib;%PATH%
-          set PATH=%VULKAN_SDK%\Include;%PATH%
+          echo "Checking Vulkan SDK installation directory..."
+          ls -l D:/a/Vesper/Vesper/VULKAN_SDK || echo "Installation path not found!"
+  
+      - name: Set VULKAN_SDK Environment Variable
+        run: echo "VULKAN_SDK=D:/a/Vesper/Vesper/VULKAN_SDK" >> $GITHUB_ENV
+      
+      - name: Force Reload Environment Variables
+        run: env
+         
+      - name: Verify VULKAN_SDK Environment Variable
+        run: |
+          echo "Verifying Vulkan SDK..."
+          echo "VULKAN_SDK=$env:VULKAN_SDK"
+          ls -l $env:VULKAN_SDK || echo "VULKAN_SDK path is incorrect!"
+  
+      - name: Debug VULKAN_SDK Variable
+        run: echo "VULKAN_SDK=$env:VULKAN_SDK"
 
-      - name: Install GLM into Vulkan SDK dependencies
+      - name: Download Vulkan Memory Allocator
         run: |
-          git clone https://github.com/g-truc/glm.git temp_glm
-          xcopy temp_glm\\glm %VULKAN_SDK%\\Include\\glm /E /H /C /I
-          rmdir /S /Q temp_glm
-
-      - name: Install Vulkan Memory Allocator (VMA) into Vulkan SDK dependencies
+          echo "Downloading Vulkan Memory Allocator header..."
+          mkdir -p $env:VULKAN_SDK/Include/vma
+          curl -L https://raw.githubusercontent.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/master/include/vk_mem_alloc.h -o $env:VULKAN_SDK/Include/vma/vk_mem_alloc.h
+      
+      - name: Download GLM Math Library
         run: |
-          git clone https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator.git temp_vma
-          xcopy temp_vma\\include\\vma.h %VULKAN_SDK%\\Include\\vma /E /H /C /I
-          rmdir /S /Q temp_vma
+          echo "Cloning GLM Math Library..."
+          mkdir -p $env:VULKAN_SDK/Include/glm
+          git clone --depth 1 https://github.com/g-truc/glm.git temp_glm
+          cp -r temp_glm/glm/* $env:VULKAN_SDK/Include/glm
+          Remove-Item temp_glm -Recurse -Force
+      
+      - name: Verify VMA and GLM Headers in Vulkan SDK
+        run: |
+          echo "Checking VMA and GLM headers in Vulkan SDK..."
+          ls -l $env:VULKAN_SDK/Include/vma || echo "VMA header not found!"
+          ls -l $env:VULKAN_SDK/Include/glm || echo "GLM headers not found!"
 
       - name: Build solution
         run: |
